name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # As per project requirements

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --no-audit
    
    - name: Check package structure
      run: |
        if [ -f "package.json" ] && [ -d "creates" ] && [ -d "triggers" ]; then
          echo "✓ Basic repository structure looks good"
          exit 0
        else
          echo "✗ Repository structure check failed"
          exit 1
        fi 